---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-files
data:
  50x.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Error</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>An error occurred.</h1>
    <p>Sorry, the page you are looking for is currently unavailable.<br/>
    Please try again later.</p>
    <p>If you are the system administrator of this resource then you should check
    the error log for details.</p>
    <p><em>Faithfully yours, nginx.</em></p>
    </body>
    </html>

  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Hello, World</title>
      <style type="text/css">
        html {
          color-scheme: light dark;
        }
      </style>
    </head>
    <body>
      <h1>Hello, World</h1>
      <p>This test is working!</p>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-cm-deployment
  name: nginx-cm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-cm-deployment
  template:
    metadata:
      labels:
        app: nginx-cm-deployment
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: nginx-cm-deployment
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: nginx-html
      volumes:
        - name: nginx-html
          configMap:
            name: nginx-html-files
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-cm-deployment
  name: nginx-cm-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-cm-deployment
  type: NodePort
